---
title: "Ideas for Modules"
format: 
  html:
    toc: true
    toc-depth: 3            
    toc-location: left      
    embed-resources: true   
    theme: cosmo
---

## Powerlifting Data

Powerlifting is a strength sport where participants compete to lift the heaviest weight. Competitors compete within weight classes, so their opponents are around the same weight as them. The sport consists of three different lifts: Squat, Bench, and Deadlift.

A sample of competitive Powerlifting data is available on the SCORE Data Repository at [https://data.scorenetwork.org/powerlifting/openpowerlifting.html](https://data.scorenetwork.org/powerlifting/openpowerlifting.html){target="_blank"}


::: {.callout-note collapse="true" title="Module Ideas" appearance="minimal"}

There are several modules in development based on this data (using polynomial regression and non-linear least squares to explore the relationship between lifting weight and age). However, there are also several other modules that could be created with these data. 

Here is a quick list of other potential modules.

- One-Way ANOVA: Comparing weight lifted across Age-classes 

- Matched pairs CI: Squat vs Deadlift

- Correlations: Exploring correlations between the three lifts

- Multicolinearity: VIFs for predicting Squat using Deadlift and Bench (and other stuff as needed)

- SLR: Relationship between body weight and lift amount

:::

## Baseball Data

Several Good Sources available on the [Data Repository](https://data.scorenetwork.org/){target="_blank"}.

- Baseball Savant Subsets

Baseball Savant has a huge amount of data available. The following two links contain subsets of these data to be more easily used in a classroom setting.

  + [Star Pitchers](https://data.scorenetwork.org/baseball/mlb_ten_pitchers_statcast.html){target="_blank"}
  + [Star Hitters](https://data.scorenetwork.org/baseball/mlb_superstar_hitters_2024.html){target="_blank"}

::: {.callout-note collapse="true" title="Module Ideas" appearance="minimal"}
Modules could probably be built around the following statistical topics.

+ Frequency tables, bar charts, proportions, conditional distributions
+ Mean, median, standard deviation, histograms, boxplots, shape of distribution
+ Side-by-side visualizations, comparing means/proportions, two-group comparisons
+ Longitudinal comparisons, trend detection, consistency metrics
:::



