name: Generate index.html for GitHub Pages

on:
  push:
    paths:
      - 'docs/*.html'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate index.html
        run: |
          mkdir -p docs
          echo '<!DOCTYPE html><html><head><title>Index</title></head><body><h1>Available Pages</h1><ul>' > docs/index.html
          for file in docs/*.html; do
            name=$(basename "$file")
            if [ "$name" != "index.html" ]; then
              echo "<li><a href=\"$name\">$name</a></li>" >> docs/index.html
            fi
          done
          echo '</ul></body></html>' >> docs/index.html

      - name: Commit and push index.html
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.html
          git commit -m "Auto-update index.html [skip ci]" || echo "No changes"
          git push
